.bp
.nr PO 1i
.CD
.ps 14
.B "List of Equations"
.sp
.DE
.XS
.sp 0.5
List of Equations
.XE
.sp 1
.ps 12
.vs 20
.po 1.1i
.ll 6i
.ta 0i 6iR
.ds eqtitle Equation Number 	 Page No.
.B "\\*[eqtitle]"
.br
.ds entry 1. A linear equation (2.1.1) \t . . .1
.pdfhref L -D eq2.1.1 \*[entry]
.br
.ds entry 2. A long mathematical series (2.1.2) \t . . .2
.pdfhref L -D eq2.1.2 \*[entry]
.br
.ds entry 3. Example matrix equation (2.1.3) \t . . .2
.pdfhref L -D eq2.1.3 \*[entry]
.br
.bp
