#!/bin/bash

#sed -i 's/function/\\m[pink]function\\m[]/' $1
#sed -i 's/end$/\\m[pink]end\\m[]/' $1
#sed -i 's/for/\\m[pink]for\\m[]/' $1
#sed -i 's/else/\\m[pink]else\\m[]/' $1
#sed -i 's/^\s*if/\\m[pink]&\\m[]/' $1

# Highlight bash functions
sed -i 's/^.*()/\\m[red]&\\m[]/' $1

# Highlights bash variables
#sed -i 's/$[a-z]*/\\m[purple]&\\m[]/' $1

# Highlights comments in a different color
commentchar="#"
sed -i 's/^\s*'"$commentchar"'.*/\\m[comment]&\\m[]/' $1

# Adds an invisible character to the beginning of
# every line so new lines get numbered
sed -i -e 's/^/\\\&/' $1
