.bp
.ps 18
.vs 20
.ll 450000u
\fBList of Equations\fR
.sp 1
.ps 13
1\h'|1.5'
.pdfhref L -D eq1 -X A linear equation
.toc-entry 5
2\h'|1.5'
.pdfhref L -D eq2 -X A linear equation
.toc-entry 5
3\h'|1.5'
.pdfhref L -D eq3 -X A linear equation
.toc-entry 5
4\h'|1.5'
.pdfhref L -D eq4 -X A linear equation
.toc-entry 5
5\h'|1.5'
.pdfhref L -D eq5 -X A linear equation
.toc-entry 5
6\h'|1.5'
.pdfhref L -D eq6 -X A linear equation
.toc-entry 5
7\h'|1.5'
.pdfhref L -D eq7 -X A linear equation
.toc-entry 5
8\h'|1.5'
.pdfhref L -D eq8 -X A linear equation
.toc-entry 5
9\h'|1.5'
.pdfhref L -D eq9 -X A linear equation
.toc-entry 5
10\h'|1.5'
.pdfhref L -D eq10 -X A linear equation
.toc-entry 5
11\h'|1.5'
.pdfhref L -D eq11 -X A linear equation
.toc-entry 5
12\h'|1.5'
.pdfhref L -D eq12 -X A linear equation
.toc-entry 5
13\h'|1.5'
.pdfhref L -D eq13 -X A long mathematical series
.toc-entry 5
14\h'|1.5'
.pdfhref L -D eq14 -X Example matrix equation
.toc-entry 6
15\h'|1.5'
.pdfhref L -D eq14 -X Equation
.toc-entry 6
16\h'|1.5'
.pdfhref L -D eq15 -X Equation
.toc-entry 6
.bp
