.bp
.footer "" "" "%"
.ps 18
.vs 20
.ll 450000u
\fBContents\fR
.sp 1
.ps \n[font-size]
\fB
1\h'0.5'
.pdfhref L -D head1 -X First Section
.toc-entry-main 2
\h'|0.7c'1.1\h'0.5'
.pdfhref L -D head1.1 -X Pythogoram Theorem
.toc-entry 2
\h'|0.7c'1.2\h'0.5'
.pdfhref L -D head1.2 -X Pythogoram Theorem
.toc-entry 2
\h'|0.7c'1.3\h'0.5'
.pdfhref L -D head1.3 -X Pythogoram Theorem
.toc-entry 2
\h'|0.7c'1.4\h'0.5'
.pdfhref L -D head1.4 -X Pythogoram Theorem
.toc-entry 2
\h'|0.7c'1.5\h'0.5'
.pdfhref L -D head1.5 -X Pythogoram Theorem
.toc-entry 2
\h'|0.7c'1.6\h'0.5'
.pdfhref L -D head1.6 -X Pythogoram Theorem
.toc-entry 2
\h'|0.7c'1.7\h'0.5'
.pdfhref L -D head1.7 -X Pythogoram Theorem
.toc-entry 2
\h'|0.7c'1.8\h'0.5'
.pdfhref L -D head1.8 -X Pythogoram Theorem
.toc-entry 2
\fB
2\h'0.5'
.pdfhref L -D head2 -X Second Section
.toc-entry-main 2
\h'|0.7c'2.1\h'0.5'
.pdfhref L -D head2.1 -X Subsection
.toc-entry 2
\fB
3\h'0.5'
.pdfhref L -D head3 -X Last Section
.toc-entry-main 6
\h'|0.7c'3.1\h'0.5'
.pdfhref L -D head3.1 -X Links using .pdfhref
.toc-entry 6
\h'|1.6c'3.1.1\h'0.5'
.pdfhref L -D head3.1.1 -X Internet Hyperlinks
.toc-entry 6
\h'|1.6c'3.1.2\h'0.5'
.pdfhref L -D head3.1.2 -X PDF links
.toc-entry 6
\h'|0.7c'3.2\h'0.5'
.pdfhref L -D head3.2 -X Table example
.toc-entry 6
.bp
