#! /bin/sh


# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
#sxhkd &
feh --bg-scale ~/Pictures/Wallpapers/Cars/Formula-One-Sports-Wallpaper-For-Desktop-Background.jpg
$HOME/.config/polybar/custom/./launch.sh
#picom
picom --config ~/.config/picom-jonaburg.conf &
redshift -P -O 3250
/usr/lib/xfce4/notifyd/xfce4-notifyd &


#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        1
bspc config window_gap          7
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config paddingless_monocle  true

bspc monitor -d I II III IV V VI VII VIII IX X

xinput set-prop  "PixArt Dell MS116 USB Optical Mouse" "libinput Natural Scrolling Enabled" 0
xinput set-prop  "PixArt Dell MS116 USB Optical Mouse" "libinput Accel Speed" 0.15

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

exec xdo raise -N Polybar
exec xdo raise -a top_bar
exec xdo raise -a bottom_bar
